---
- name: Install python3, docker and docker-compose
  hosts: docker_server
  become: true
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python #here using python2 to install python3
      yum:
        name: 
        - python3
        - docker
        update_cache: true
        state: present
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      systemd:
        name: docker
        state: started    

- name: Add ec2-user to docker group
  hosts: docker_server
  become: true
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
    - name: Reconnecting session so Docker group can add
      meta: reset_connection

- name: Test docker pull
  hosts: docker_server
  tasks:
    - name: pull redis
      command: docker pull redis